background #000000
foreground #cdd6f4

cursor #89b4fa
cursor_text_color #000000

selection_background #313244
selection_foreground #cdd6f4

color0  #000000
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #cba6f7
color6  #94e2d5
color7  #bac2de

color8  #45475a
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #cba6f7
color14 #94e2d5
color15 #ffffff

background_opacity 1.0
